# Generated by Django 5.1 on 2023-11-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('logo', models.TextField()),
                ('phone', models.TextField()),
                ('history', models.TextField()),
                ('cod_geography', models.TextField()),
            ],
        ),
    ]
