# Generated by Django 5.1 on 2023-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_empresa_address_alter_empresa_cod_geography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
